DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'analyst_role') THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM analyst_role';
        EXECUTE 'REVOKE USAGE ON SCHEMA public FROM analyst_role';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user_role') THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM app_user_role';
        EXECUTE 'REVOKE USAGE ON SCHEMA public FROM app_user_role';
        EXECUTE 'REVOKE USAGE ON ALL SEQUENCES IN SCHEMA public FROM app_user_role';
    END IF;
END
$$;

DROP ROLE IF EXISTS analyst_role;
DROP ROLE IF EXISTS app_user_role;

CREATE ROLE analyst_role NOLOGIN;
GRANT USAGE ON SCHEMA public TO analyst_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO analyst_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO analyst_role;

CREATE ROLE app_user_role NOLOGIN;
GRANT USAGE ON SCHEMA public TO app_user_role;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO app_user_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO app_user_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user_role;